dist: bionic
sudo: required

language: python

cache: pip

# used for caching purposes
services:
  - redis-server

python:
  # After upgrading to Ubuntu 18.04 we lost ability to test against Py3.5
  # - 3.5
  # Python3.6 doesn't allow for pickling logger objects, and this functionality
  # is required for autoemails application
  # - 3.6
  - 3.7
  - 3.8

env:
  - CHECK_MIGRATION=true

install:
  - pip install -r requirements.txt

before_script:
  - if [[ $CHECK_MIGRATION == true ]]; then
      python manage.py makemigrations --dry-run --check;
      export STATUS_CODE=$?;
      if [[ "$STATUS_CODE" != "0" ]]; then
        exit 1;
      fi;
    fi;

script:
  - python manage.py test -v 2
