version: '3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: amy
      POSTGRES_PASSWORD: amypostgresql
      POSTGRES_DB: amy
    ports:
      - "5432:5432"
    # volumes:
    #   - ../docker/database:/var/lib/postgresql/data

  redis:
    command: redis-server --appendonly yes
    image: redis:latest
    ports:
      - "6379:6379"
    # volumes:
    #   - ../docker/redis:/data

  amy:
    build: .
    image: amy:latest
    environment:
      - AMY_REDIS_URL=redis://redis:6379/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/amy
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis

  rqworker:
    image: amy:latest
    environment:
      - AMY_REDIS_URL=redis://redis:6379/
    command: python manage.py rqworker -v 2
    depends_on:
      - redis
      - amy

  rqscheduler:
    image: amy:latest
    environment:
      - AMY_REDIS_URL=redis://redis:6379/
    command: python manage.py rqscheduler -v 2
    depends_on:
      - redis
      - amy
      - rqworker
